import {
  LayoutDashboard, Users, Briefcase, Building2, ListChecks, ClipboardList, CalendarCheck,
  CalendarClock, Award, Bell, Megaphone, FileText, ScrollText, BarChart3, History, User,
  UserPlus, ClipboardList,
} from 'lucide-react';

export const navByRole = {
  super_admin: [
    { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/interns', label: 'Interns', icon: Users },
    { to: '/employees', label: 'Employees', icon: Briefcase },
    { to: '/departments', label: 'Departments', icon: Building2 },
    { to: '/candidates', label: 'Candidates', icon: UserPlus },
    { to: '/applications', label: 'Applications', icon: ClipboardList },
    { to: '/tasks', label: 'Tasks', icon: ListChecks },
    { to: '/worklogs', label: 'Work Logs', icon: ClipboardList },
    { to: '/attendance', label: 'Attendance', icon: CalendarCheck },
    { to: '/leaves', label: 'Leaves', icon: CalendarClock },
    { to: '/performance', label: 'Performance', icon: Award },
    { to: '/announcements', label: 'Announcements', icon: Megaphone },
    { to: '/documents', label: 'Documents', icon: FileText },
    { to: '/certificates', label: 'Certificates', icon: ScrollText },
    { to: '/reports', label: 'Reports', icon: BarChart3 },
    { to: '/audit-logs', label: 'Audit Logs', icon: History },
  ],
  hr: [
    { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/interns', label: 'Interns', icon: Users },
    { to: '/employees', label: 'Employees', icon: Briefcase },
    { to: '/departments', label: 'Departments', icon: Building2 },
    { to: '/candidates', label: 'Candidates', icon: UserPlus },
    { to: '/applications', label: 'Applications', icon: ClipboardList },
    { to: '/tasks', label: 'Tasks', icon: ListChecks },
    { to: '/worklogs', label: 'Work Logs', icon: ClipboardList },
    { to: '/attendance', label: 'Attendance', icon: CalendarCheck },
    { to: '/leaves', label: 'Leaves', icon: CalendarClock },
    { to: '/performance', label: 'Performance', icon: Award },
    { to: '/announcements', label: 'Announcements', icon: Megaphone },
    { to: '/documents', label: 'Documents', icon: FileText },
    { to: '/certificates', label: 'Certificates', icon: ScrollText },
    { to: '/reports', label: 'Reports', icon: BarChart3 },
    { to: '/audit-logs', label: 'Audit Logs', icon: History },
  ],
  team_lead: [
    { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/interns', label: 'My Interns', icon: Users },
    { to: '/tasks', label: 'Tasks', icon: ListChecks },
    { to: '/worklogs', label: 'Work Logs', icon: ClipboardList },
    { to: '/attendance', label: 'Attendance', icon: CalendarCheck },
    { to: '/leaves', label: 'Leave Requests', icon: CalendarClock },
    { to: '/performance', label: 'Performance', icon: Award },
    { to: '/announcements', label: 'Announcements', icon: Megaphone },
  ],
  intern: [
    { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/tasks', label: 'My Tasks', icon: ListChecks },
    { to: '/worklogs', label: 'Work Logs', icon: ClipboardList },
    { to: '/attendance', label: 'Attendance', icon: CalendarCheck },
    { to: '/leaves', label: 'Leaves', icon: CalendarClock },
    { to: '/performance', label: 'My Performance', icon: Award },
    { to: '/announcements', label: 'Announcements', icon: Megaphone },
    { to: '/documents', label: 'Documents', icon: FileText },
    { to: '/certificates', label: 'Certificates', icon: ScrollText },
    { to: '/profile', label: 'My Profile', icon: User },
  ],
};
